### ISSUE TITLE
Ansible command and playbooks result in cryptography warning

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/docker-debian8-ansible#2]
Whenever I run Ansible commands I get:

```
[WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'
```

No functional issue, just annoying. It looks like it's because of: https://github.com/ansible/ansible/issues/13075 and https://github.com/ansible/ansible/issues/16790

I can fix with a pip install of `cryptography`.

**Comment by russellvt** [comment]
Note that this error means that the module was throwing an exception, not that it was missing. You can generally squelch it by upgrading the cryptography module.
